language: python

dist: xenial

cache: false

sudo: false

python:
  - "3.6"
  - "3.7"
  - "3.8"
  - "3.9"

before_install:
  - sudo apt-get update
  - pip install -r requirements.txt
  - pip install --upgrade -r requirements.txt

install:
  - python setup.py install

script:
  - coverage run -m py.test alg3dpy
  - coverage report

after_success:
  - coveralls

notifications:
  email:
    on_success: change
    on_failure: change

